<?php

/**
 * @file
 * Contains autotag.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityFieldManager;
use Drupal\node\Entity\Node;
use Drupal\field\FieldConfigInterface;
use Drupal\taxonomy\Entity\Term;
use Drupal\taxonomy\Entity\Vocabulary;
use Drupal\taxonomy\TermInterface;
use Drupal\taxonomy\VocabularyInterface;

/**
 * Implements hook_help().
 */
function autotag_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the autotag module.
    case 'help.page.autotag':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Implements the Tags API to help link entities to terms already present on a site.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function autotag_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $entityManager = Drupal::service('entity.manager');
  $source_fields = array();
  $destination_fields = array();

  if ($form_id == 'node_type_add_form' || $form_id == 'node_type_edit_form') {
    $form['autotag'] = array(
      '#type' => 'details',
      '#group' => 'additional_settings',
      '#title' => t('Autotag'),
    );

    $type = $form['type']['#default_value'];

    $fields = $entityManager->getFieldDefinitions('node', $type);

    foreach ($fields as $field){
      if ($field->getType() == 'text_with_summary' || $field->getType() == 'text_long') {
        $source_fields[$field->getName()] = $field->getLabel();
      }
      if ($field->getType() == 'entity_reference' && $field->getSettings()['target_type'] == 'taxonomy_term') {
        $destination_fields[$field->getName()] = $field->getLabel();
      }
    }
    if ($type) {
      $default_source = \Drupal::config('autotag.type.' . $type)->get('source');
      $default_destination = \Drupal::config('autotag.type.' . $type)->get('destination');
    }

    $form['autotag']['autotag_source_field'] = array(
      '#type' => 'select',
      '#title' => t('Source fields to get text:'),
      '#default_value' => $default_source,
      '#options' => $source_fields,
      '#access' => TRUE,
      '#description' => t('Text field.'),
    );

    $form['autotag']['autotag_destination_field'] = array(
      '#type' => 'select',
      '#title' => t('Destination fields to get text:'),
      '#default_value' => $default_destination,
      '#options' => $destination_fields,
      '#access' => TRUE,
      '#description' => t('Text field.'),
    );

    array_unshift($form['actions']['submit']['#submit'], 'autotag_form_submit_handler');
  }

}

/**
 * Implements hook_form_submit().
 */
function autotag_form_submit_handler($form, FormStateInterface $form_state) {
  $type = $form_state->getValue('type');
  $source = $form_state->getValue('autotag_source_field');
  $destination = $form_state->getValue('autotag_destination_field');
  \Drupal::configFactory()->getEditable('autotag.type.' . $type)
    ->set('source' , $source)
  ->save();
  \Drupal::configFactory()->getEditable('autotag.type.' . $type)
    ->set('destination' , $destination)
    ->save();
}

/**
 * Implements hook_node_presave().
 */
function autotag_node_presave(EntityInterface &$node)  {
  $type = $node->bundle();
  $source = \Drupal::config('autotag.type.' . $type)->get('source');
  $text = '';
  $destination = \Drupal::config('autotag.type.' . $type)->get('destination');
  $vocabularies = $node->getFieldDefinition($destination)->getItemDefinition()->getSettings()['handler_settings']['target_bundles'];
  $text_array = $node->get($source)->getValue();
  foreach ($text_array as $item) {
    if (isset($item['summary'])){
      $text .= strtolower($item['summary']);
    }
    if (isset($item['value'])){
      $text .= strtolower($item['value']);
    }
  }
  foreach ($vocabularies as $vocabulary) {
    $tree = \Drupal::getContainer()->get('entity.manager')->getStorage('taxonomy_term')->loadTree($vocabulary);
    foreach ($tree as $term){
      $found = strpos($text, strtolower($term->name));
      if ($found !== FALSE){
        $node->{$destination}[] = ['target_id' => $term->tid];
      }
    }
  }
  
}