autotag.type.*:
  type: config_entity
  label: 'Content type'
  mapping:
    source:
      type: secuence
      label: 'List of source fields to search terms.'
      sequence:
        type: autotag.autotag_field.[%key]
    destination:
      type: string
      label: 'Machine-readable name of destination taxonomy refference field.'